version: '3.0'
services:
  mariadb:
    image: mariadb
    container_name: thot-database-production
    volumes:
      - thot-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lemontech
    ports:
      - 3306:3306
    networks:
      webapp:
        ipv4_address: 25.0.0.2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: thot-phpmyadmin-production
    environment:
      PMA_HOST: 25.0.0.2
    links:
      - "mariadb:mysql"
    ports:
      - 7000:80
    networks:
      webapp:
        ipv4_address: 25.0.0.3
  siwa:
    build: ./siwa
    container_name: siwa-app-production
    ports:
      - 8090:4567
    networks:
      webapp:
        ipv4_address: 25.0.0.4
  thot-ui:
    build: ./thot-ui
    container_name: thot-ui-production
    ports:
      - 80:80
    environment:
      NGINX_PORT: 80
    depends_on:
      - thot
    networks:
      webapp:
        ipv4_address: 25.0.0.5
  thot:
    build: ./thot
    container_name: thot-app-production
    links:
      - "mariadb:mysql"
    ports:
      - 8080:3000
    depends_on:
      - mariadb
      - siwa
    networks:
      webapp:
        ipv4_address: 25.0.0.6
volumes:
  thot-database:
networks:
  webapp:
    driver: bridge
    ipam:
      config:
        - subnet: 25.0.0.0/24
